### ISSUE TITLE
64-bit Version and Portable Version?

### ISSUE THREAD

**Issue by hl2guide** [brhinescot/Cropper#14]
This app looks really interesting, please consider releasing a 64-bit and portable version 💃

**Comment by brhinescot** [comment]
I'm finishing up some DPI aware work right now. I will probably release both 32 and 64-bit versions then. As far as making it portable, there was a PR a while back that added portable support to Cropper. If you add a file named cropper.portable to the install directory Cropper will use it to store config data and save everything in that folder. You can then copy the folder to a thumb drive or whatever. I need to update the docs too, not sure if that is in there.
