### ISSUE TITLE
Capture off center when using Scale and Layout increase

### ISSUE THREAD

**Issue by hockeyfreak** [brhinescot/Cropper#8]
In windows 10, when using 125% or 150%, the center of the capture becomes more and more off as you increase.  Just an annoyance, but changing back to 100% every time you want to capture is a pain. Any fix for this?

**Comment by brhinescot** [comment]
Thanks for the feedback. I have an issue open already for supporting high DPI monitors that will address this.

**Comment by brhinescot** [comment]
#7
